#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service
SERVICE_NAME="bulwark"

bulwark_bootstrap_filesystem

if bulwark_mode_enabled lite ; then
    service_stop 20-bulwark
    custom_files "${CONTAINER_CUSTOM_PATH}" "${NGINX_WEBROOT}" "${NGINX_USER}" "${NGINX_GROUP}"
    bulwark_generate_lite_config
elif bulwark_mode_enabled relay && ! bulwark_mode_enabled full ; then
    service_stop 20-bulwark
else
    custom_files "${CONTAINER_CUSTOM_PATH}" "/app" "${BULWARK_USER}" "${BULWARK_GROUP}"
fi

if ! bulwark_mode_enabled relay ; then
    service_stop 30-relay
fi

custom_scripts

liftoff
